name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nightcap-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/nightcap-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nightcap-frontend:latest ./frontend/nightcap-ui
          docker push ${{ secrets.DOCKER_USERNAME }}/nightcap-frontend:latest

      - name: Create Docker network
        run: docker network create nightcap-net

      - name: Run backend container
        run: |
          docker run -d --name nightcap-backend \
            --network nightcap-net \
            -p 8000:8000 \
            ${{ secrets.DOCKER_USERNAME }}/nightcap-backend:latest

      - name: Run frontend container
        run: |
          docker run -d --name nightcap-frontend \
            --network nightcap-net \
            -p 3000:3000 \
            ${{ secrets.DOCKER_USERNAME }}/nightcap-frontend:latest
